export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST'
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS'
export const USER_FETCH_FAILURE = 'USER_FETCH_FAILURE'

export const USER_FETCH_TOKEN_REQUEST = 'USER_FETCH_TOKEN_REQUEST'
export const USER_FETCH_TOKEN_SUCCESS = 'USER_FETCH_TOKEN_SUCCESS'
export const USER_FETCH_TOKEN_FAILURE = 'USER_FETCH_TOKEN_FAILURE'

export const USER_PROFILE_FETCH_REQUEST = 'USER_PROFILE_FETCH_REQUEST'
export const USER_PROFILE_FETCH_SUCCESS = 'USER_PROFILE_FETCH_SUCCESS'
export const USER_PROFILE_FETCH_FAILURE = 'USER_PROFILE_FETCH_FAILURE'

export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'

export const PROFILE_FETCH_REQUEST = 'PROFILE_FETCH_REQUEST'
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS'
export const PROFILE_FETCH_FAILURE = 'PROFILE_FETCH_FAILURE'

export const SETTINGS_FETCH_REQUEST = 'SETTINGS_FETCH_REQUEST'
export const SETTINGS_FETCH_SUCCESS = 'SETTINGS_FETCH_SUCCESS'
export const SETTINGS_FETCH_FAILURE = 'SETTINGS_FETCH_FAILURE'